### ISSUE TITLE
Rubric breakdown report tab is visible to students

### ISSUE THREAD

**Issue by Richardvi** [marcusgreen/moodle-report_advancedgrading#14]
**Describe the bug**

**To Reproduce**
1. Go to an assignment as a student
2. Click on rubric breakdown report
3. See error

![image](https://github.com/marcusgreen/moodle-report_advancedgrading/assets/5486910/d9db1031-219a-4f59-ba5a-009ec5e5f272)

Moodle 4.3.2

Of course the error is correct, students don't have access to the report. But they should not see the option at all, because now they will click on it and report an error.

**Comment by marcusgreen** [comment]
Thanks Richard, good description. I will look into it.

**Comment by marcusgreen** [comment]
I did a commit yesterday 

https://github.com/marcusgreen/moodle-report_advancedgrading/commit/934adcc14b9f58f428a2b37bd3a1a5e3d0707710

That should address this issue. If you have a test site and are happy with using code from Github please test it for me to confirm it does what you want. Otherwise I will post here when I have tested further and pushed to the moodle.org plugins database.

**Comment by Richardvi** [comment]
Yep, tested it and that seems to work perfectly. The good thing is that not only the 'Rubric Breakdown Report' for students has gone, but also the extra 'assignment' tab - which did nothing but redirect you to where you already were :)

Thanks Marcus!

**Comment by marcusgreen** [comment]
Yea!, what name can I add to the readme credits, Richard who ?

**Comment by Richardvi** [comment]
Richard van Iwaarden, thought you knew from the Moodle forums haha

But credit should be all yours for investing time to create a plugin!

**Comment by marcusgreen** [comment]
I was fairly sure it was you, particularly as I recognised something from a screen shot but it is good to be clear. Every useful bit of feedback helps to improve the plugin, makes me look good and helps out other users. Thanks again

**Comment by marcusgreen** [comment]
I am in the process of releasing a version to the plugins database confirming 4.4 compatibility. I am closing this as that commit resolves it and I am about to take another look at your issue here.
https://github.com/marcusgreen/moodle-report_advancedgrading/issues/15

Thank you for the feedback.
