### ISSUE TITLE
Support for Ranged Rubrics

### ISSUE THREAD

**Issue by dmitriim** [marcusgreen/moodle-report_advancedgrading#16]
Recently we have developed a new Ranged rubrics plugin see https://github.com/catalyst/moodle-gradingform_rubric_ranges

Would be nice to get a support for this one as well.

**Comment by marcusgreen** [comment]
This file illustrates how I added the rubric flex support 
https://github.com/marcusgreen/moodle-report_advancedgrading/blob/main/rubref.php

I am on annual leave in Japan at the moment (attending a moot). But I will be back next week and we can collaborate further.

**Comment by dmitriim** [comment]
Seems like fixed.
