### ISSUE TITLE
Bug: User group data is not exported 

### ISSUE THREAD

**Issue by sumaiyamannan** [marcusgreen/moodle-report_advancedgrading#18]
**Describe the bug**
When groups are being used in an assignment, the data exported does not account for it, it only lists the user in a group who had submitted the assignment. 

**To Reproduce**
Go to course add assignment with 
- 'Grade' as 'Rubric' 
- 'Submission type' as 'Online text' 
- 'Group submission settings' as 'Student submit in groups: Yes'
Go to assign -> Advanced grading, and add grading template 

Login as a few students and make submission
Go to assignment submission and grade a few submissions
Go to assignment and click more 'Rubric breakdown report' 

**Expected behavior**
In the exported CSV file, it should list:
- Every student details and grade
- Also have a separate column for 'group'
Like the way it is listed on the Assignment -> View all submissions pages

View the below screenshots for reference:
Assignment -> More ->  'Rubric breakdown report'
![Screenshot from 2024-03-14 12-32-21](https://github.com/marcusgreen/moodle-report_advancedgrading/assets/43946803/ebcfe631-6395-401e-a97a-305936400b44)

Assignment -> View all submissions
![Screenshot from 2024-03-14 12-32-04](https://github.com/marcusgreen/moodle-report_advancedgrading/assets/43946803/23009868-560f-4763-b021-7b0673f66c7f)

**Comment by marcusgreen** [comment]
I am actively looking into https://github.com/marcusgreen/moodle-report_advancedgrading/issues/19
And preparing to confirm Moodle 4.4 compatibility. I will look at this issue when I have completed those two tasks. I will update this ticket then.

**Comment by marcusgreen** [comment]
I have closed https://github.com/marcusgreen/moodle-report_advancedgrading/issues/19
And confirmed that the tests run on the master branch (soon to be Moodle 4.4). This issue is now the next in line for me to look at.

**Comment by sumaiyamannan** [comment]
@marcusgreen agreed, this is what I have mentioned as the expected behavior in the first comment, i.e. for all the students to be listed. 
Yes, it would be good to make the columns sortable in the report itself. However when the report is exported as a csv, the columns can be sorted using an application like excel or Libreoffice.

**Comment by marcusgreen** [comment]
Just to be absolutely clear, you mean all students on the course including those that have not submitted anything to the assignment. I am almost certain that is what you mean, because that is what I thought of, but I want to double check.

**Comment by sumaiyamannan** [comment]
Yeah this is what I meant .. 
Ah ok I did not realize the complexity to achieve it.

**Comment by marcusgreen** [comment]
To explain further, it was designed with the focus on just showing details of who had submitted. That seemed very logical at the time, but in retrospect it would have been good to have all students who could have submitted but have not, because people often want to chase them to make a submission.. But re-doing it would be quite complex.
