### ISSUE TITLE
Only active grading instances should be shown

### ISSUE THREAD

**Issue by juancs** [marcusgreen/moodle-report_advancedgrading#19]
**Describe the bug**
Several advanced grading methods checks for INSTANCE_STATUS_INCOMPLETE (0) status of the grading instance showing results that are not accurante with the real status of the graded user.

That status means:

> The grader started grading but did clicked neither submit nor cancel

I don't think this status is the most correct. In fact I've arrived to a situation where a student is not graded but the report keeps showing me some grades in a rubric criteria.

INSTANCE_STATUS_ACTIVE (1) seems to be a more appropiate flag to check for. In fact, this is something that is already done in btec.php.

**Comment by marcusgreen** [comment]
That sounds very interesting. I will take a look at your code.

**Comment by marcusgreen** [comment]
I have merged your code, thank you for your contribution. I like to mention contributors in the readme file here https://github.com/marcusgreen/moodle-report_advancedgrading/blob/main/changelog.md

Can I mention you and what name should I use. Thanks again

**Comment by juancs** [comment]
Yes... of course :-) 

Juan Segarra Montesinos is ok :-)

Thank you :-)
