### ISSUE TITLE
Site level reporting of Advanced Grading

### ISSUE THREAD

**Issue by mifantrax** [marcusgreen/moodle-report_advancedgrading#2]
This is not a bug, just a possible enhancement question.

Would it be helpful and possible to extend this report to cover all courses in a specific year for example?

Thank you!

**Comment by marcusgreen** [comment]
That is a good question, site wide (or multi course) reports are highly desirable but they tend to come with a significant, performance overhead. Assuming you can live with or mitigate that overhead (e.g. make it for a set number of courses, such as a single course category),  where would it "appear". At the moment it is linked to a specific assignment, but how would you tell it which course/asssignmentts you would pull it from.

Anyway I may have mis-interpreted your question so come back to me and let me know what you think.

**Comment by marcusgreen** [comment]
Ahh yes, a site level course with restrictions makes some sense. .For example if you had a site wide report on assignments using the rubric grading method, different assignments use different criteria so I am not sure how you would present the data. It could be simplified to show the name of the user, Then a line break followed by the names of all the assignment with the final grade for that student next to each one.... (or similar).

Give me your thoughts on how you would like such a report.

**Comment by marcusgreen** [comment]
Closing this as beyond the scope that I am willing to work on.
