### ISSUE TITLE
headers in grading report occasionally do not match the data itself

### ISSUE THREAD

**Issue by danmarsden** [marcusgreen/moodle-report_advancedgrading#22]
The order of printing the headers in the report doesn't always seem to match the data itself. In some cases we've seen weird behavior and the titles of some columns have been swapped.

Getting the criteriarecord to populate in the right order in the $data array seems to fix this. (PR incoming.)

**Comment by marcusgreen** [comment]
Thanks Dan I will look into it and your code.
