### ISSUE TITLE
The plugin don't apply the filters everywhere

### ISSUE THREAD

**Issue by izendegi** [marcusgreen/moodle-report_advancedgrading#3]
Hi,

We are testing this plugin (which is great, btw) and we've detected that there are some places inside the plugin where the Moodle filters aren't applied, at least these:

- The assignment name in the breadcrumb
- The course, the assignment and the rubric names in the header table
- The rubric criteria and level definitions

![irudia](https://user-images.githubusercontent.com/5556433/205008774-d5f134de-fd55-40df-a40d-249fc03f5e5c.png)

**Comment by izendegi** [comment]
I've just done a PR with the kind of stuff needed to support the filters: #4

**Comment by marcusgreen** [comment]
Hi izendegi, this is excellent, I had assumed you were commenting on Wordselect, which still doesn't process the mlang tags properly, especially if you use images. I was not aware/had not tested the advanced grading report properly with mlang (shame on me as someone who only speaks English). I will look at your code and get back to you as soon as possible.

**Comment by marcusgreen** [comment]
I forgot to close this, Merged into main on 1 Dec 2022, thank you izendegi
