### ISSUE TITLE
A strings isn't localized

### ISSUE THREAD

**Issue by izendegi** [marcusgreen/moodle-report_advancedgrading#5]
I've seen that there is a string in the header, the one which tells which the grading method is, that isn't localized:

![irudia](https://user-images.githubusercontent.com/5556433/205008598-920f8dc5-52c2-4cd4-9d09-577d039ff0d5.png)

I think that the values there are rubric and marking guide, in that case I believe that these core strings can be used for that localization:
gradingform_guide | pluginname 
gradingform_rubric | pluginname

**Comment by marcusgreen** [comment]
Closing as I have merged in your code. I will mention you in my next changelog update. Many thanks for raising the issue and providing a solution.
